services:
  evolu-relay:
    container_name: evolu-relay-server
    image: evolu/relay:latest
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - evolu/relay:latest
    ports:
      - "${RELAY_PORT:-4000}:${RELAY_PORT:-4000}"
    volumes:
      # Use named volume by default, can be overridden with bind mount if needed
      - evolu-relay-data:/app/data
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - LOG_LEVEL=${LOG_LEVEL:-error}
      - RELAY_NAME=${RELAY_NAME:-evolu-relay}
      - RELAY_PORT=${RELAY_PORT:-4000}
      - RELAY_ENABLE_LOGGING=${RELAY_ENABLE_LOGGING:-false}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-1G}
          cpus: ${CPU_LIMIT:-1.0}
        reservations:
          memory: ${MEMORY_RESERVED:-512M}
          cpus: ${CPU_RESERVED:-0.5}
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:4000",
        ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: ${LOG_MAX_SIZE:-50m}
        max-file: ${LOG_MAX_FILES:-5}
    networks:
      - evolu-network

volumes:
  evolu-relay-data:
    driver: local
    name: evolu-relay-data

networks:
  evolu-network:
    name: evolu-relay-network
    driver: bridge
